FROM continuumio/miniconda3:23.3.1-0

#############################################
##      System updates                     ##
#############################################

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install wget git bzip2 libcurl4-gnutls-dev gcc python3-dev python3-pip libmariadb-dev && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG C.UTF-8

#############################################
##      Create the webapp environment      ##
#############################################

# Create conda environment (Python version 3.10.10)
COPY ./environment-dev.yml /tmp/environment-dev.yml
RUN conda env create -f /tmp/environment-dev.yml

# Pull the environment name out of the environment-dev.yml
RUN echo "source activate $(head -1 /tmp/environment-dev.yml | cut -d' ' -f2)" > ~/.bashrc
ENV PATH /opt/conda/envs/$(head -1 /tmp/environment-dev.yml | cut -d' ' -f2)/bin:$PATH

# Install requirements.txt
COPY ./requirements.txt /tmp/requirements.txt
RUN python -m pip install -r /tmp/requirements.txt

#############################################
##      Add caper webapp code              ##
#############################################

ARG AMPLICON_ENV_PORT
ARG AA_USER

RUN useradd -rm -d /home/${AA_USER} -s /bin/bash -g root -G sudo -u 1001 ${AA_USER} && \
    chown ${AA_USER}:${AA_USER} -R /home/${AA_USER}
USER ${AA_USER}
COPY ./caper/ /home/${AA_USER}/code/caper/

#############################################
##      Start web server code              ##
#############################################

WORKDIR /home/${AA_USER}/code/caper
EXPOSE ${AMPLICON_ENV_PORT}
CMD echo "Hello world" && \
    python --version && \
    echo "" && \
    echo "Conda environment list" && \
    conda env list && \
    conda list && \
    echo "" && \
    echo "pip freeze" && \
    python -m pip freeze && \
#    echo "--------" && \
#    echo "cat ~/.bashrc" && \
#    cat ~/.bashrc && \
    python manage.py runserver 0.0.0.0:8000

