version: "3"

services:

  amplrepdev:
    build:
      context: .
      dockerfile: Dockerfile_dev
      args:
        AMPLICON_ENV_PORT: ${AMPLICON_ENV_PORT:-8000}
        AA_USER: ${AA_USER:-amprepouser}
    image: genepattern/amplicon-repo:dev-test
    container_name: amplicon-repo
#    restart: always
    env_file: config.sh
    environment:
      - MONGO_DB_NAME=${DB_NAME:-caper}
      - DB_URI=${DB_URI}
      - AMPLICON_ENV=${AMPLICON_ENV:-dev}
      - AMPLICON_ENV_PORT=${AMPLICON_ENV_PORT:-8000}
      - GOOGLE_SECRET_KEY=${GOOGLE_SECRET_KEY}
      - GLOBUS_SECRET_KEY=${GLOBUS_SECRET_KEY}
    ports:
      - '8000:8000'
    volumes:
      - ${PWD}/.aws:/root/.aws
      - ${PWD}/logs:/srv/logs
      - ${PWD}:/home/${AA_USER:-amprepouser}/code
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:4
    hostname: mongodb
    env_file: config.sh
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-caper}
    volumes:
      - ${PWD}/data:/data/db
    #      - ${PWD}/docker/_mongo/fixtures:/import
    #      - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - '27017:27017'

networks:
  default:

