version: "3.9"

services:

  amplrepdev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AA_USER: $AA_USER
        UID: $UID
        GID: $GID
        ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS: ${ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS}
        GOOGLE_SECRET_KEY: ${GOOGLE_SECRET_KEY}
        GLOBUS_SECRET_KEY: ${GLOBUS_SECRET_KEY}
        ACCOUNT_DEFAULT_HTTP_PROTOCOL: ${ACCOUNT_DEFAULT_HTTP_PROTOCOL}
        SECURE_SSL_REDIRECT: ${SECURE_SSL_REDIRECT}
        DB_URI: ${DB_URI}
        S3_FILE_DOWNLOADS: ${S3_FILE_DOWNLOADS}
        AWS_PROFILE_NAME: ${AWS_PROFILE_NAME}
        S3_DOWNLOADS_BUCKET_PATH: ${S3_DOWNLOADS_BUCKET_PATH}
    image: genepattern/amplicon-repo:${AMPLICON_ENV}
    container_name: ${CONTAINER_NAME}
    restart: always
    privileged: true
    # .env is not need to be specified, all the variales will be set as environment parameters in the container
    # however if you specify .env then you can see all the variables if you do docker-compose -f docker-compose-dev.yml config
    env_file: .env
    ports:
      - '${AMPLICON_ENV_PORT}:8000'
    volumes:
      - ${PWD}/.aws:/tmp/.aws:ro
      - ${PWD}/logs:/logs
      # might want to mount the temp files on the local machine
      - ${PWD}/tmp:/tmp
      - ${PWD}/.git:/srv/.git
      # mount your code
      - ${PWD}:/srv/:rw
    user: "${UID}:${GID}"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - ${PWD}/data:/data/db
    ports:
      - '27017:27017'

networks:
  default:

