FROM continuumio/miniconda3:23.3.1-0

#############################################
##      Arguments                          ##
#############################################

ARG AA_USER
ARG ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS
ARG GOOGLE_SECRET_KEY
ARG GLOBUS_SECRET_KEY
ARG ACCOUNT_DEFAULT_HTTP_PROTOCOL
ARG SECURE_SSL_REDIRECT
ARG DB_URI
ARG S3_FILE_DOWNLOADS
ARG AWS_PROFILE_NAME
ARG S3_DOWNLOADS_BUCKET_PATH
ARG S3_STATIC_FILES

#############################################
##      System updates                     ##
#############################################

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install wget git bzip2 libcurl4-gnutls-dev gcc python3-dev python3-pip libmariadb-dev && \
    apt-get purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG C.UTF-8

#############################################
##      Create the webapp environment      ##
#############################################

# Create conda environment (Python version 3.10.10)
COPY ./environment-dev.yml /tmp/environment-dev.yml
RUN conda env create -f /tmp/environment-dev.yml

# Pull the environment name out of the environment-dev.yml
RUN echo "source activate $(head -1 /tmp/environment-dev.yml | cut -d' ' -f2)" > ~/.bashrc
ENV PATH /opt/conda/envs/$(head -1 /tmp/environment-dev.yml | cut -d' ' -f2)/bin:$PATH

# Install requirements.txt
COPY ./requirements.txt /tmp/requirements.txt
RUN python -m pip install -r /tmp/requirements.txt

#############################################
##      Add caper webapp code              ##
#############################################

RUN useradd -rm -d /home/${AA_USER} -s /bin/bash -g root -G sudo -u 1001 ${AA_USER}
USER ${AA_USER}
COPY ./caper/ /srv/caper/

#############################################
##      Start web server code              ##
#############################################

WORKDIR /srv/caper
EXPOSE 8000
CMD echo "Hello world" && \
    python --version && \
    echo "" && \
    echo "Conda environment list" && \
    conda env list && \
    python manage.py runserver 0.0.0.0:8000

