name: caperenv
channels:
  - anaconda
  - anaconda-fusion
  - defaults
dependencies:
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - krb5=1.19.2
  - libcurl=7.82.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libnghttp2=1.46.0
  - libssh2=1.10.0
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=22.1.2
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
#  - pip
#  - pip:
#    - -r requirements.txt
