name: Weekly Report

on:
  schedule:
    - cron: '0 15 * * 4' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script 
        env:
          AMPLICON_ENV: ${{ secrets.AMPLICON_ENV }}
          AMPLICON_ENV_PORT: ${{ secrets.AMPLICON_ENV_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_URI_SECRET: ${{ secrets.DB_URI_SECRET }}
          MAILJET_API: ${{ secrets.MAILJET_API }}
          MAILJET_SECRETKEY: ${{ secrets.MAILJET_SECRETKEY }}
          MAILJET_EMAIL: ${{ secrets.MAILJET_EMAIL }}
        run: python caper/weekly-report.py
